### ISSUE TITLE
Add a whitelist

### ISSUE THREAD

**Issue by YoSijo** [systemli/ansible-role-needrestart#8]
I have a lot of systems with services that like to change. New Service Units from Users and other stuff.
A blacklist is therefore rather difficult to implement.
Therefore a whitelist with services that I would like to restart would be better.
If she then understands regex, a dream comes true. ;)

**Comment by xshadow** [comment]
Hey YoSijo, thank you for your feedback. That is not an option at the moment.  It's simply not integrated in needrestart yet. See https://github.com/liske/needrestart/issues/135 . To build ansible logic around it to solve that problem, seems not to be the correct way of doing.

**Comment by xshadow** [comment]
You should support the ticket there. If it is implemented, we can add the logic.

**Comment by YoSijo** [comment]
Thank you, I will address the mentioned ticket on the "needrestart" project.
